site_name: webtool
repo_name: ds5105119/webtool
site_url: https://ds5105119.github.io/webtool/
repo_url: https://github.com/ds5105119/webtool/
edit_uri: edit/main/docs/

theme:
  name: 'material'
  logo: https://raw.githubusercontent.com/ds5105119/logo/refs/heads/main/logowithR%20square.png
  favicon: https://raw.githubusercontent.com/ds5105119/logo/refs/heads/main/logo%20round.png
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - header.autohide
    - navigation.tabs
    - navigation.expand
    - navigation.path
    - search.suggest
    - search.highlight
    - toc.follow

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: grey
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  # Python Markdown
  abbr:
  admonition:
  attr_list:
  footnotes:
  md_in_html:
  tables:
  toc:
    permalink: true

  # Python Markdown Extensions
  pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
  pymdownx.details:
  pymdownx.inlinehilite:
  pymdownx.snippets:
  pymdownx.superfences:
  pymdownx.blocks.details:
  pymdownx.blocks.tab:
    alternate_style: True


plugins:
  search:

  mkdocstrings:
    handlers:
      python:
        options:
          show_if_no_docstring: true
          inherited_members: true
          members_order: source
          separate_signature: true
          unwrap_annotated: true
          filters:
            - '!^_'
          docstring_section_style: spacy
          signature_crossrefs: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          merge_init_into_class: true

nav:
  - Home:
    - index.md
  - Reference:
    - Auth:
      - JWT Manager: reference/auth/manager.md
      - JWT Service: reference/auth/service.md
      - Backend: reference/throttle/backend.md
    - Throttle:
      - Decorator: reference/throttle/decorator.md
      - Limiter: reference/throttle/limiter.md
      - Middleware: reference/throttle/middleware.md
    - Cache:
      - Client: reference/cache/client.md
      - Lock: reference/cache/lock.md
    - Utils:
      - Key: reference/utils/key.md
      - Json: reference/utils/json.md

  - Resources:
    - resources/CONTRIBUTING.md
