site_name: webtool

theme:
  name: 'material'
  logo: https://raw.githubusercontent.com/ds5105119/logo/refs/heads/main/logowithR%20square.png
  favicon: https://raw.githubusercontent.com/ds5105119/logo/refs/heads/main/logo%20round.png
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
  palette:
    # Palette toggle for light mode
    - scheme: default
    - primary: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
    - primary: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
