site_name: webtool
site_url: https://ds5105119.github.io/webtool/
repo_url: https://github.com/ds5105119/webtool/

theme:
  name: 'material'
  logo: https://raw.githubusercontent.com/ds5105119/logo/refs/heads/main/logowithR%20square.png
  favicon: https://raw.githubusercontent.com/ds5105119/logo/refs/heads/main/logo%20round.png
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - header.autohide
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: white
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: ko
          name: 한국어
          build: true

nav:
  - Home:
    - index.md
  - Learn:
      - JWT:
          - docs/manager.md
          - docs/service.md
  - Resources:
      - resources/CONTRIBUTING.md
