name: CD

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.11' ]
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build dependencies for requests in python 3.9
        run: sudo apt-get install libxml2-dev libxslt-dev
        
      - name: Install Poetry
        uses: snok/install-poetry@v1
        
      - name: Install dependencies
        run: |
          poetry install

      - name: Poetry config
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}

      - name: Build package
        run: |
          poetry build

      - name: Publish package
        run: |
          poetry publish
